import type { AssessmentSession } from "@/lib/assessment/session"

/**
 * Builds the full report prompt for Sonnet.
 * This is the primary AI output — a comprehensive Exit IQ Report in Markdown.
 */
export function buildReportPrompt(session: AssessmentSession): string {
  const s1 = session.stage1 ?? {}
  const gate = session.gate ?? {}
  const s2 = session.stage2 ?? {}
  const s3 = session.stage3 ?? {}
  const s4 = session.stage4 ?? {}

  return `You are an expert M&A advisor specializing in small business exits under $10M.
Generate a comprehensive Exit IQ Report in Markdown for the following business assessment.
Be specific, actionable, and empathetic. Use concrete numbers where possible. Do not be generic.

## Seller Information
- Name: ${gate.firstName ?? "Business Owner"}
- Email: ${gate.email ?? "N/A"}
- Selling Timeline: ${gate.sellingTimeline ?? "Not specified"}
- Segment: ${gate.tag ?? "Not specified"}

## Stage 1: Business Snapshot
- Industry: ${s1.industry ?? "Not specified"}
- Years in Business: ${s1.years ?? "Not specified"}
- Annual Revenue: ${s1.revenue ?? "Not specified"}
- Seller's Discretionary Earnings (SDE): ${s1.sde ?? "Not specified"}
- Employees: ${s1.employees ?? "Not specified"}
- State: ${s1.state ?? "Not specified"}

## Stage 2: Business Health
- Owner Dependency: ${s2.ownerDependency ?? "Not specified"}
- Customer Concentration: ${s2.customerConcentration ?? "Not specified"}
- Revenue Trend: ${s2.revenueTrend ?? "Not specified"}
- Recurring Revenue: ${s2.recurringRevenue ?? "Not specified"}
- Financial Documentation: ${s2.docReadiness ?? "Not specified"}
- Real Estate Situation: ${s2.realEstate ?? "Not specified"}
- Reason for Selling: ${s2.reasonForSelling ?? "Not specified"}

## Stage 3: Deal Risk Factors
- SBA Restricted Industry: ${s3.sbaRestricted ?? "Not specified"}
- Key Person Risk: ${s3.keyPersonRisk ?? "Not specified"}
- SOPs / Documentation: ${s3.sops ?? "Not specified"}
- Growth Levers: ${s3.growthLevers ?? "Not specified"}
- Legal Issues: ${s3.legal ?? "Not specified"}

## Stage 4: Deal Expectations
- Asking Price: ${s4.askingPrice ?? "Not specified"}
- Deal Structures Considered: ${(s4.dealStructure ?? []).join(", ") || "Not specified"}
- Urgency: ${s4.urgency ?? "Not specified"}
- Broker Status: ${s4.brokerStatus ?? "Not specified"}

---

Generate a detailed Exit IQ Report in Markdown with the following sections:

# Exit IQ Report — ${gate.firstName ?? "Business Owner"}

## Executive Summary
A 3–4 sentence overview of this business's exit readiness and the key opportunity.

## Valuation Analysis
Provide a realistic valuation range based on the SDE, industry multiples, and revenue. Explain the methodology briefly.

## Strength Highlights
List 3–5 specific strengths as bullet points, with brief explanation of why each matters to buyers.

## Key Risk Factors
List 3–5 specific risks as bullet points. Be honest but constructive — explain the buyer impact of each risk.

## 90-Day Action Plan
A prioritized list of 5–8 concrete actions the seller should take in the next 90 days to maximize their exit value. Each item should be actionable and specific.

## Deal Structure Recommendations
Based on the seller's goals and risk profile, recommend 1–2 deal structures with brief rationale.

## SBA Financing Assessment
Whether the business likely qualifies for SBA 7(a) financing and what that means for the buyer pool.

## Timeline to Close
A realistic estimate of how long a deal will take given the current state of the business.

---
*Report generated by Exit IQ — powered by AI*
`
}

/**
 * Builds the teaser prompt for Haiku.
 * Returns a short structured card shown before the full report.
 */
export function buildTeaserPrompt(session: AssessmentSession): string {
  const s1 = session.stage1 ?? {}
  const gate = session.gate ?? {}
  const s2 = session.stage2 ?? {}
  const s3 = session.stage3 ?? {}

  return `You are an expert M&A advisor for small business exits under $10M.
Based on the following business snapshot, generate a teaser card for a seller.
Be concise, specific, and use realistic market language.

## Business Snapshot
- Industry: ${s1.industry ?? "Not specified"}
- Years in Business: ${s1.years ?? "Not specified"}
- Revenue Band: ${s1.revenue ?? "Not specified"}
- SDE Band: ${s1.sde ?? "Not specified"}
- Employees: ${s1.employees ?? "Not specified"}
- State: ${s1.state ?? "Not specified"}
- Revenue Trend: ${s2.revenueTrend ?? "Not specified"}
- Recurring Revenue: ${s2.recurringRevenue ?? "Not specified"}
- Owner Dependency: ${s2.ownerDependency ?? "Not specified"}
- SBA Restricted: ${s3.sbaRestricted ?? "Not specified"}
- Legal Issues: ${s3.legal ?? "Not specified"}
- Segment Tag: ${gate.tag ?? "Not specified"}

Generate a JSON object with these exact fields:
- headline: A compelling 1-sentence summary of this business's exit opportunity (max 15 words)
- valuationRange: A realistic valuation range string, e.g. "$1.2M – $1.8M"
- topStrength: The single biggest strength that will attract buyers (1 sentence)
- topRisk: The single most important risk to address before going to market (1 sentence)
- segmentTag: One of "hot_seller", "warm_explorer", "nurture", or "burned_by_broker" based on the seller's profile

Be specific and based on actual market conditions for this industry and size.`
}
