import type { Question } from "@/components/onboarding/types"

export const SELLER_QUESTIONS: Question[] = [
  {
    id: "role",
    headline: "What brings you to Scorta?",
    sub: "We'll personalize your experience.",
    type: "cards",
    options: [
      { value: "seller", label: "I want to sell my business", sub: "Get an AI exit analysis & list your deal" },
      { value: "buyer", label: "I want to buy a business", sub: "Browse AI-vetted listings & make offers" },
    ],
  },
  {
    id: "industry",
    headline: "What industry are you in?",
    sub: "We'll apply the right valuation benchmarks.",
    type: "cards",
    options: [
      { value: "home_services", label: "Home Services", sub: "HVAC, plumbing, cleaning, landscaping" },
      { value: "food_bev", label: "Food & Beverage", sub: "Restaurants, catering, food manufacturing" },
      { value: "healthcare", label: "Healthcare", sub: "Medical, dental, physical therapy" },
      { value: "retail", label: "Retail / Fitness", sub: "Stores, studios, franchises" },
      { value: "manufacturing", label: "Manufacturing", sub: "Industrial, fabrication, production" },
      { value: "professional", label: "Professional Services", sub: "Accounting, legal, consulting, staffing" },
      { value: "tech", label: "Technology / SaaS", sub: "Software, digital products, agencies" },
      { value: "other", label: "Something else", sub: "We cover most industries" },
    ],
  },
  {
    id: "revenue",
    headline: "What's your annual revenue?",
    sub: "Last full fiscal year is perfect.",
    type: "cards",
    options: [
      { value: "under_250", label: "Under $250K" },
      { value: "250_500", label: "$250K – $500K" },
      { value: "500_1m", label: "$500K – $1M" },
      { value: "1m_3m", label: "$1M – $3M" },
      { value: "3m_10m", label: "$3M – $10M" },
      { value: "over_10m", label: "Over $10M" },
    ],
  },
  {
    id: "years",
    headline: "How long have you been operating?",
    sub: "Longer history = stronger deal profile.",
    type: "cards",
    options: [
      { value: "under_2", label: "Less than 2 years" },
      { value: "2_5", label: "2 – 5 years" },
      { value: "5_10", label: "5 – 10 years" },
      { value: "over_10", label: "10+ years" },
    ],
  },
  {
    id: "timeline",
    headline: "When are you thinking of selling?",
    sub: "No wrong answer — this helps us prioritize.",
    type: "cards",
    options: [
      { value: "asap", label: "As soon as possible", sub: "Ready to list now" },
      { value: "6mo", label: "Within 6 months", sub: "Actively preparing" },
      { value: "1yr", label: "Within a year", sub: "Getting the groundwork done" },
      { value: "exploring", label: "Just exploring", sub: "Want to know my options" },
    ],
  },
  {
    id: "concerns",
    headline: "What matters most to you?",
    sub: "Select all that apply.",
    type: "chips",
    multi: true,
    options: [
      { value: "price", label: "Getting the best price" },
      { value: "speed", label: "Closing fast" },
      { value: "confidential", label: "Keeping it confidential" },
      { value: "transition", label: "Smooth team transition" },
      { value: "no_broker", label: "Avoiding broker fees" },
      { value: "understand", label: "Understanding the process" },
      { value: "financing", label: "Seller financing options" },
      { value: "legacy", label: "Finding the right buyer" },
    ],
  },
  {
    id: "contact",
    headline: "Last step — where do we send your results?",
    sub: "Your Exit IQ report is generated instantly. Free, always.",
    type: "contact",
  },
]
